name: Publishing Docs

on:
  push:
    branches: [ main ]  # 或者您的默认分支名
    paths:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
jobs:
  build:
    if: github.repository == 'DeePTB-Lab/dpnegf'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_book_theme linkify-it-py
        pip install myst-nb jupyter
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
    - name: Build docs
      run: |
        cd docs
        python conf.py
        sphinx-build -b html . _build/html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
